name = "apea-aiken-batch-1/crowdfunding_b"
version = "0.0.0"
compiler = "v1.1.7"
plutus = "v3"
license = "Apache-2.0"
description = "Aiken contracts for project 'apea-aiken-batch-1/crowdfunding_b'"

[repository]
user = "apea-aiken-batch-1"
project = "crowdfunding_b"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "0f88f8ffce60b91ae3e4b3a3f40bab153e494760"
source = "github"

[[dependencies]]
name = "aiken-extra/time_util"
version = "5.210.202409"
source = "github"

[[dependencies]]
name = "aiken-extra/tx_util"
version = "1.215.202411"
source = "github"

[config.default]
state_token = "STATE_TOKEN"
